/* Generated By:JavaCC: Do not edit this line. CGIFParserConstants.java */
package cgif.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CGIFParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LBRACE = 8;
  /** RegularExpression Id. */
  int RBRACE = 9;
  /** RegularExpression Id. */
  int LPAREN = 10;
  /** RegularExpression Id. */
  int RPAREN = 11;
  /** RegularExpression Id. */
  int LBRACKET = 12;
  /** RegularExpression Id. */
  int RBRACKET = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int QUESTIONMARK = 15;
  /** RegularExpression Id. */
  int STAR = 16;
  /** RegularExpression Id. */
  int COMMA = 17;
  /** RegularExpression Id. */
  int ATSIGN = 18;
  /** RegularExpression Id. */
  int POUNDSIGN = 19;
  /** RegularExpression Id. */
  int LESSTHAN = 20;
  /** RegularExpression Id. */
  int GREATERTHAN = 21;
  /** RegularExpression Id. */
  int BAR = 22;
  /** RegularExpression Id. */
  int DOUBLEQUOTE = 23;
  /** RegularExpression Id. */
  int TYPE = 24;
  /** RegularExpression Id. */
  int SUBTYPE = 25;
  /** RegularExpression Id. */
  int FORALL = 26;
  /** RegularExpression Id. */
  int DIST = 27;
  /** RegularExpression Id. */
  int COLL = 28;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 29;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 30;
  /** RegularExpression Id. */
  int HEX_LITERAL = 31;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 32;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 33;
  /** RegularExpression Id. */
  int EXPONENT = 34;
  /** RegularExpression Id. */
  int QUOTED_STRING = 35;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;
  /** RegularExpression Id. */
  int LETTER = 38;
  /** RegularExpression Id. */
  int PART_LETTER = 39;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"?\"",
    "\"*\"",
    "\",\"",
    "\"@\"",
    "\"#\"",
    "\"<\"",
    "\">\"",
    "\"|\"",
    "\"\\\"\"",
    "<TYPE>",
    "\"subtype\"",
    "\"@every\"",
    "\"@dist\"",
    "\"@coll\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<QUOTED_STRING>",
    "<CHARACTER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
  };

}
